export const actions = {
  GET_SEARCHED_PRODUCTS: 'GET_SEARCHED_PRODUCTS',
  GET_PRODUCT: 'GET_PRODUCT',
  GET_DESCRIPTION: 'GET_DESCRIPTION',
  GET_BREAD_CRUMBS: 'GET_BREAD_CRUMBS',
  GET_FILTERED_PRODUCTS: 'GET_FILTERED_PRODUCTS',
};
