export const actions = {
  SET_MATCHED_PRODUCTS: 'SET_MATCHED_PRODUCTS',
  SET_PRODUCT: 'SET_PRODUCT',
  SET_DESCRIPTION: 'SET_DESCRIPTION',
  SET_BREADCRUMBS: 'SET_BREADCRUMBS',
  SET_FILTERED_PRODUCTS: 'SET_FILTERED_PRODUCTS',
};
